// default package
// Generated Mar 4, 2014 9:07:27 AM by Hibernate Tools 3.6.0

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private Integer id;
	private String name;

	public State() {
	}

	public State(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
